---
title: "Paulo Fagandini, PhD"
date: today
date-format: "MMMM D, YYYY" 
format:
  html:
    toc: true
    toc-location: left
    #theme: cosmo
    css: styles.css
  pdf:
    documentclass: article
    geometry: 
        - margin=1in
        - a4paper
    fontsize: 10pt
    mainfont: roboto
    include-in-header:
      text: |
        \usepackage{titling}
        \pretitle{\vspace{-3cm}\begin{center}\LARGE\bfseries}
        \posttitle{\end{center}\vspace{-1.5cm}}
        \predate{}
        \postdate{}
        \date{}
        
---

::: {.contact-info}
**Email:** [pfagandini@iscal.ipl.pt](mailto:pfagandini@iscal.ipl.pt) | [paulo.fagandini@novasbe.pt](mailto:paulo.fagandini@novasbe.pt) | [paulo.ruiz@uevora.pt](mailto:paulo.ruiz@uevora.pt)

**Website:** [pfagandini.github.io](https://pfagandini.github.io)

**Born:** March 26, 1986 – Viña del Mar, Chile | **Citizenship:** Chilean / Italian

**ORCID:** 0000-0002-5386-2160 | **Ciência ID:** 4011-5942-8AAD  
**SCOPUS ID:** 57224823274 | **IDEAS:** pfa431
:::

---

## Areas of Specialization

Applied Microeconomic Theory | Computational Economics

---

## Appointments

**2021–present** — Assistant Professor (Adjunct – Full Time)  
Lisbon Accounting and Business School, Polytechnic University of Lisbon

**2023–present** — Assistant Professor (Adjunct – Part Time)  
Nova School of Business and Economics, NOVA University Lisbon

**2025–present** — Assistant Professor (Adjunct – Part Time)  
Faculty of Social Sciences and Technology, Universidade Europeia

**2021–present** — Research Member  
Center for Advanced Studies in Management and Economics

**2018–2020** — Postdoctoral Fellow  
Nova School of Business and Economics, NOVA University Lisbon

---

## Academic Degrees

**2018** — Ph.D. in Economics  
Nova School of Business and Economics, UNL

**2014** — M.Res. in Economics  
Nova School of Business and Economics, UNL

**2011** — B.Sc. in Economics  
School of Economics and Business - UChile

---

## Grants, Honors & Awards

### Grants and Scholarships

**2015–2018** — Fundação para a Ciência e a Tecnologia (FCT)  
Doctoral Grant: SFRH/BD/105669/2015

**2011–2015** — Nova SBE Scholarship for merit (Partial tuition waiver)

---

## Research

### Peer Reviewed Publications

Fagandini P., and Dierickx I. (2023). Computing Profit-Maximizing Bid Shading Factors in First-Price Sealed-Bid Auctions. *Computational Economics*, 61(3), 1009-1035. [https://doi.org/10.1007/s10614-022-10321-y](https://doi.org/10.1007/s10614-022-10321-y)

Fagandini, P. (2022). Wealth and the principal–agent matching. *Managerial and Decision Economics*, 43(2), 555–568. [https://doi.org/10.1002/mde.3402](https://doi.org/10.1002/mde.3402)

### Book Chapters

Fagandini, P. (2024). Implementing the Agent ID Model and Simulation Results. In: Gomes, O., Lins de Moraes, M., Fagandini, P. (eds) The Agent ID Model. Integrated Science, vol 32. Springer, Cham. [https://doi.org/10.1007/978-3-031-75996-3_10](https://doi.org/10.1007/978-3-031-75996-3_10)

### Working Papers

"Surviving the Perfect Storm: Exports, Fiscal Austerity, and Firm Heterogeneity." (2020, joint with M. Adelino, M.A. Ferreira, Francisco Queiró)

"Hunting with two bullets; Moral Hazard with a Second Chance." (2018) Nova SBE WP 629

### Conferences and Seminars

**2018** — RG, Nova SBE, Lisbon PT; DEA-UIB, Palma ES; PEJ Meeting 2018, Lisbon PT*

**2017** — UECE Lisbon Meetings, Lisbon PT*; NOVA Doctoral School, UNL, Lisbon PT; IRW, Nova SBE, Lisbon PT; RG, Nova SBE, Lisbon PT

**2016** — QEDJ 2016, Amsterdam NE; ASSET Annual Meeting 2016, Thessaloniki GR*

*\* Peer Reviewed*

### Other Communications

#### Teaching Materials

**2020** — "Writing a full LaTeX document from Scratch" (EN)  
Online Course available at Udemy.com – 7 hours course

#### Press Coverage

**20-Jan-2020** — "Fornecedores do Estado fizeram o milagre das exportações"  
*Jornal de Negócios* (PT)

**7-Jan-2020** — "Surviving the Perfect Storm: Exports, Fiscal Austerity, and Firm Heterogeneity"  
*The FinReg Blog*, Global Financial Markets Center, School of Law, Duke University

#### Speaker in Conferences, Seminars, and Special Lectures

**29-Oct-2021** — "Os desafios das empresas num contexto de incerteza: Perspetivas multivariadas"  
Lisbon Accounting and Business School - IPL (PT)

---

::: {.content-visible when-format="pdf"}
\clearpage
:::

## Teaching Experience

### Course Coordinator (Regências)

  - **2018-present** Bridging Mathematics, PhD. in Economics and Finance, Nova SBE, UNL.
  - **2022-present** Math & Stats, MSc. in Economics, Finance, Business Analytics, and International Development & Public Policy, Nova SBE, UNL.
  - **2026-present** Microeconomia - Plano de Transição, BSc. in Accounting and Administration, ISCAL, IPL.

### Instructor

The language in which the name of the course appears, reveals the teaching languange.

**2025-present** — Faculty of Social Sciences and Technology, UE

- B.Sc.: Economics of Tourism, Economics

**2021–present** — Lisbon Accounting and Business School, IPL

- B.Sc.: Microeconomia, Statistics I, Statistics II, Principios de Macroeconomia

**2018–present** — Nova School of Business and Economics, UNL

- Ph.D.: Bridging Mathematics
- M.Sc.: Math and Stats

**2025** — Prague University of Economics and Business, CZ (Visiting)

- M.Sc./B.Sc.: Economics of Incentives for Policy and Politics (22-hour intensive course)

### Teaching Assistant

**2013–present** — Nova School of Business and Economics, UNL

- M.Sc. (Grader): Digital Experimentation & Causal Analysis, Financial Management, Advanced Financial Management, Financial Management for Entrepreneurs, Machine Learning, Advanced Industrial Organization, Organization and Incentives, Economics of Regulation, Game Theory
- B.Sc. (TA): Econometrics, Finance ,Industrial Organization, Advanced Microeconomics, Macroeconomics

**2008–2010** — School of Economics and Business, UChile

- B.Sc. (Head TA): Introducción a Macroeconomía, Macroeconomía I
- B.Sc. (TA): Macroeconomía I, Macroeconomía II

### Thesis Supervision

**2025 Spring** — Markus Relbo, MSc. Finance - Nova SBE
  
---

## Other Education

**2023** — Commercial Engineering – Professional Title  
Approved with distinction. School of Economics & Business - UChile

**2019** — "Stata Econometrics Winter School 2019"  
Timberlake, FEP Universidade do Porto

**2017** — Summer School: "Liquidity in Financial Markets and Institutions"  
Finance Theory Group, Olin Business School, Washington University

**Fall 2016** — Visiting Ph.D. Student  
European Center for Advanced Research in Economics and Statistics, Université libre de Bruxelles

**2015** — Workshop: "Pedagogical Training for College Teachers"  
NOVA Medical School, UNL

---

::: {.content-visible when-format="pdf"}
\clearpage
:::

## Other Professional Experience

**2023** — External Consultant  
TimWe.Tech

**2014–2015** — Senior Consultant  
I.D. Consulting Limited

**2011** — Trainee Program  
Pro-Chile Milano (IT), Directorate of Economic Relations of the Ministry of Foreign Affairs of Chile (6 months)

---

## Skills

**Software:** Windows, Office (Advanced MS Excel), Linux (Debian based), Git, Mathematica

**Programming Languages:** Stata, Python, SQL, Java, LaTeX, MATLAB/Octave, R

**Languages:** Spanish (native), English and Portuguese (fluent), Italian (intermediate)

---

## Academic Service

### Referee

Information Economics and Policy, Managerial and Decision Economics, Computational Economics, Portuguese Economic Journal, Theory and Decision, PLOS One.

### Editor

**2024** — Gomes, O., Lins de Moraes, M., Fagandini, P. (eds) The Agent ID Model. Integrated Science, vol 32. Springer, Cham. https://doi.org/10.1007/978-3-031-75996-3

### Conference Chairs

**2017** — UECE Lisbon Meetings in Game Theory and Applications  
Session: Matching II

**2016** — ASSET Annual Meeting 2016  
Session: Asymmetric Information I

### Scientific Committee Member

**2023** 2nd International Conference CEMEERS-2023b. 

### Thesis Jury Participation

* **2025/2026 Fall**
  * President for Vicente Mesquita Silvério Ferra Esteves, *Guinanos x Brave Generation Academy: Pilot Project for E-Learning Teacher Training Program in Guinea-Bissau*, MSc. International Development and Public Policy - Nova SBE.
  * Discussant for Francesca Scalfi, *The Determinants of Childbearing Leave Take-up*, MSc. Economics - Nova SBE
  * Discussant for Isabella Stolcis, *A contribution to the Economics of Workplace Absences in Portugal*, MSc. Economics - Nova SBE
  * Discussant for Theodor Dietrich Helmut Knöbig, *Artificial Intelligence and Democracy: Analysis and Evidence*, MSc. Business Analytics - Nova SBE
* **2024/2025 Fall**
  * President for Laura Gomes Garcia, *Unlocking the Potential: Challenges, Opportunities, and Strategic Pathways for Global Gateway Facility in Central America*, MSc. International Development and Public Policy - Nova SBE.
  * President for Sofia Isabel de Albuquerque Silva Antunes de Morais, *Need-Based Financial Aid in Higher Education: The Case of Portugal*, MSc. International Development and Public Policy - Nova SBE.
  * President for Verena Luisa Epp, *Towards developing a competition and regulatory framework for digital markets*, MSc. Economics - Nova SBE
  * Discussant for Marco Passalacqua, *IRS Jovem: Bridging Generations - Analyzing the Intergenerational Impact of an Innovative Fiscal Policy in Portugal* , MSc. International Development and Public Policy - Nova SBE
  * Discussant for Elisabetta D'alessandro, *IRS Jovem: Fostering Youth Empowerment Through Innovative Fiscal Strategies*, MSc. International Development and Public Policy - Nova SBE
  * Discussant for João Miguel Iláco Pacheco, *IRS Jovem as a Tool for Socioeconomic Stability: Opportunities and Limitations in Tax Policy for Young Adults*, MSc. International Development and Public Policy - Nova SBE
* **2023/2024 Fall**
  * President for Sofia Isabel Antunes de Morais, *Need-based Financial Aid in Higher Education: The Case of Portugal*, MSc. International Development and Public Policy, Nova SBE
  * Discussant for Daniel Luzio Castelo, *Dynamic Peer Effects in the Workplace*, MSc. in Economics - Nova SBE
  * Discussant for Dario Raccagni, *The Cambridge Analytica Case: The Impact of Big Data on Political Advertising and The Implications on Political Communication Strategies and Regulations*, MSc. Business Analytics - Nova SBE

---


::: {.content-visible when-format="html"}
::: {.download-section}
[Download PDF Version](fagandini_cv.pdf){.btn .btn-primary}
:::
:::