---
title: "Review for lecture Heteroskedasticity"
format: html
---

1. Testing for Heteroskedasticity
2. Breusch-Pagan test
3. White test
4. Lazy White test
5. Weighted Least Squares (WLS)
6. Robust Standard Errors
7. Feasible Generalized Least Squares

Consider the classical model:

$$
y = X\beta + u
$$

From where we estimate $\hat{\beta}$ as

$$\hat{\beta}=(X'X)^{-1}X'y$$

Now let's compute the variance of $\hat{\beta}$

$$
\begin{aligned}
V[\hat{\beta}|X]&=V\left[(X'X)^{-1}X'y|X\right]\\
&= V\left[(X'X)^{-1}X'(X\beta+u)|X\right]\\
&=V\left[(X'X)^{-1}X'X\beta+(X'X)^{-1}X'u|X\right]\\
&=V\left[\beta+(X'X)^{-1}X'u|X\right]=V\left[(X'X)^{-1}X'u|X\right]
\end{aligned}
$$

And then

$$
V[\hat{\beta}|X]=E[(X'X)^{-1}X'uu'X(X'X)^{-1}|X]
$$

Note that if we are in the presence of homoskedasticity, then $V[u_i|X]=\sigma^2$, in particular $E[uu'|X]=\sigma^2 I_n$. With 
homoskedasticity:

$$
V[\hat{\beta}|X]=E[(X'X)^{-1}X'\sigma^2 I_n'X(X'X)^{-1}|X]=\sigma^2(X'X)^{-1}
$$

However, with heteroskedasticity:

$$
V[\hat{\beta}|X]=E[(X'X)^{-1}X'uu'X(X'X)^{-1}|X]
$$

where $E[uu'|X]$ is the variance-covariance matrix of the error, $\Omega$. If errors are uncorrelated, the covariance is zero, however the diagonal has different $\sigma_i^2$.

Note that this does not create a bias, as still $E[u|X]=0$, and we still have

$$
E[\hat{\beta}]=E\left[(X'X)^{-1}X'y|X\right]=E\left[\beta+(X'X)^{-1}X'u|X\right]=\beta+E\left[(X'X)^{-1}X'u|X\right]
$$

And the bias, $(X'X)^{-1}X'E[u|X]=0$.

Going back to $V[\hat{\beta}|X]$

$$
V[\hat{\beta}|X]=(X'X)^{-1}X'\Omega X(X'X)^{-1}
$$

Try this estimator: $\hat{\beta}_{robust}=(X'\Omega^{-1} X)^{-1}X'\Omega^{-1} y$. I will ignore the subscript $robust$ from now on, but keep in mind that $\hat{\beta}=\hat{\beta}_{robust}$:

$$
V[\hat{\beta}|X]=(X'\Omega^{-1}X)^{-1}X'\Omega^{-1}\Omega\Omega^{-1} X(X'\Omega^{-1}X)^{-1}=(X'\Omega^{-1} X)^{-1}
$$
