<!DOCTYPE html>
<html lang="en"><head>
<script src="1_intro_files/libs/clipboard/clipboard.min.js"></script>
<script src="1_intro_files/libs/quarto-html/tabby.min.js"></script>
<script src="1_intro_files/libs/quarto-html/popper.min.js"></script>
<script src="1_intro_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="1_intro_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="1_intro_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="1_intro_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <meta name="author" content="Paulo Fagandini">
  <title>Introduction and Growth Rates</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="1_intro_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="1_intro_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="1_intro_files/libs/revealjs/dist/theme/quarto-ee9ab3830bbe7759b42dda8416faf5cd.css">
  <link href="1_intro_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="1_intro_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="1_intro_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="1_intro_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link href="1_intro_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

  <script src="1_intro_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

  <script src="1_intro_files/libs/viz-1.8.2/viz.js"></script>

  <link href="1_intro_files/libs/DiagrammeR-styles-0.2/styles.css" rel="stylesheet">

  <script src="1_intro_files/libs/grViz-binding-1.0.11/grViz.js"></script>

</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Introduction and Growth Rates</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Paulo Fagandini 
</div>
        <p class="quarto-title-affiliation">
            Lisbon Accounting and Business School – Polytechnic University of Lisbon
          </p>
    </div>
</div>

</section>
<section>
<section id="course-introduction" class="title-slide slide level1 center">
<h1>Course Introduction</h1>

</section>
<section id="core-information" class="slide level2">
<h2>Core Information</h2>
<p><strong>Instructor:</strong> Paulo Fagandini</p>
<p><span class="emoji" data-emoji="email">📧</span> pfagandini@iscal.ipl.pt</p>
<p><br>
</p>
<p><strong>Main source for course material:</strong> <a href="https://moodle2526.ipl.pt/">Moodle@ISCAL</a></p>
<p><strong>Alternative source (EN):</strong> <a href="https://pfagandini.github.io/statistics1.html">pfagandini.github.io/statistics1.html</a></p>
<p><br>
</p>
<p><strong>Official communication channel:</strong> <span class="emoji" data-emoji="email">📧</span> Institutional Email</p>
</section>
<section id="bibliography" class="slide level2">
<h2>Bibliography</h2>
<h3 id="topic-1">Topic 1:</h3>
<p><span class="emoji" data-emoji="book">📖</span> The making of index numbers. 1<sup>st</sup> Ed 1922. Irving Fisher. <span class="emoji" data-emoji="book">📖</span> A Practical Introduction to Index Numbers. 1<sup>st</sup> Ed 2015. Jeff Ralph, Rob O’Neill, Joe Winton.</p>
<h3 id="topics-2-and-3">Topics 2 and 3:</h3>
<p><span class="emoji" data-emoji="book">📖</span> Statistics for Business and Economics Global Edition. 10<sup>th</sup> Ed 2022. Paul Newbold, William Carlson, and Betty Thorne.</p>
<p><br>
</p>
<p><small>This last book is a bit expensive, but it can be rented for less money <a href="https://eu.pearson.com/statistics-for-business-and-economics-global-edition/9781292438306">here</a>. The Publisher kindly offered a 25% discount with the code <strong>MISLIBROS2025</strong>. This code is valid for the whole site until December 31<sup>st</sup> , 2025.</small></p>
</section>
<section id="continuous-assessment" class="slide level2">
<h2>Continuous Assessment</h2>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Assessment Element</th>
<th>Weight (%)</th>
<th>Duration</th>
<th>Syllabus</th>
<th>Date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Midterm</td>
<td>60%</td>
<td>80 minutes</td>
<td>Topics 1 and 2</td>
<td>Week Nov 11-15 &nbsp;</td>
</tr>
<tr class="even">
<td>Partial Exam</td>
<td>40%</td>
<td>80 minutes</td>
<td>Topic 3</td>
<td>Regular Exam Date</td>
</tr>
</tbody>
</table>
<p><small>Each test has a minimum grade of 7.00 (out of 20), not 6.9, not 6.95.</small></p>
</section>
<section id="comprehensive-exam" class="slide level2">
<h2>Comprehensive Exam</h2>
<p>Students may opt, on the day of the Exam, to take an Exam worth 100% of the grade. This Exam will cover Topics 1, 2, and 3.</p>
<p><br>
</p>
<p>If you score less than 7.00 in the Midterm, or if you cannot attend the midterm for whatever reason, you <strong>will</strong> have to do the Comprehensive Exam.</p>
</section></section>
<section>
<section id="growth-rates" class="title-slide slide level1 center">
<h1>Growth Rates</h1>

</section>
<section id="example-apple-stock" class="slide level2">
<h2>Example: Apple Stock</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="1_intro_files/figure-revealjs/unnamed-chunk-1-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Source: Yahoo Finance</p>
</div><div class="column" style="width:50%;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">Date</th>
<th style="text-align: right;">Close</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2019</td>
<td style="text-align: right;">73.41</td>
</tr>
<tr class="even">
<td style="text-align: right;">2020</td>
<td style="text-align: right;">132.69</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2021</td>
<td style="text-align: right;">177.57</td>
</tr>
<tr class="even">
<td style="text-align: right;">2022</td>
<td style="text-align: right;">129.93</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2023</td>
<td style="text-align: right;">192.53</td>
</tr>
<tr class="even">
<td style="text-align: right;">2024</td>
<td style="text-align: right;">250.42</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2025</td>
<td style="text-align: right;">229.35</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></div>
</section>
<section id="example-apple-stock-1" class="slide level2">
<h2>Example: Apple Stock</h2>
<p>Let the close price for Apple be represented by the variable <span class="math inline">\(y_t\)</span>, so <span class="math inline">\(y_{2019}\)</span> is the close price we got for2019 (<em>i.e.</em> 73.41).</p>
<p>How much did <span class="math inline">\(y\)</span> grow between 2019 and 2020?</p>
<div class="fragment">
<p><span class="math display">\[\Delta y_{2020} = y_{2020} - y_{2019} = 132.69 - 73.41\]</span> <span class="math display">\[=59.28\]</span></p>
</div>
<div class="fragment">
<p>Or we could say</p>
<p><span class="math display">\[y_{2020} = y_{2019} + \Delta y_{2020}\]</span> <span class="math display">\[132.69 = 73.41 + 59.28\]</span></p>
</div>
</section>
<section id="example-apple-stock-2" class="slide level2">
<h2>Example: Apple Stock</h2>
<p><span class="math display">\[y_{2020}=y_{2019}+\Delta y_{2020}\]</span></p>
<p><span class="math display">\[y_{2020}=y_{2019}\left(1+\frac{\Delta y_{2020}}{y_{2019}}\right)\]</span></p>
<p><span class="math display">\[y_{2020}=y_{2019}\left(1+\delta^y_{2020}\right)\]</span></p>
<p>This, <span class="math inline">\(\delta_{2020}^y\)</span>, is the <strong>growth rate</strong> of <span class="math inline">\(y\)</span> at year2020.</p>
</section>
<section id="growth-rate" class="slide level2">
<h2>Growth Rate</h2>
<div class="callout callout-note no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Growth Rate</strong></p>
</div>
<div class="callout-content">
<p>Let <span class="math inline">\(y_t\)</span> be a variable that might take different values over time. The <strong>growth rate</strong> at <span class="math inline">\(t\)</span> is given by <span class="math inline">\(\delta_t^y\)</span>, and takes a value such that:</p>
<p><span class="math display">\[y_t=y_{t-1}\left(1+\delta_t\right)\]</span></p>
<p>And then</p>
<p><span class="math display">\[\delta_t = \frac{y_t-y_{t-1}}{y_{t-1}}\]</span></p>
<p><small>Note: I dropped <span class="math inline">\(y\)</span> from the notation in the formula because it is obvious that we are talking about the variable <span class="math inline">\(y\)</span>.</small></p>
<p>You can write the growth rate as a decimal or as a percentage. If you use decimal notation, consider at least 4 places, if you use percentage you use at least 2. Example: 0.0123 or 1.23%.</p>
<p><strong>Interpretation</strong>: What is the percentage change for the variable <span class="math inline">\(y\)</span> between <span class="math inline">\(t-1\)</span> and <span class="math inline">\(t\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="example" class="slide level2">
<h2>Example</h2>
<p><span class="math display">\[132.69 = 73.41+(132.69 - 73.41)\]</span></p>
<p><span class="math display">\[132.69 =73.41\left(1+\frac{59.28}{73.41}\right)\]</span></p>
<p><span class="math display">\[132.69=73.41\left(1+0.8075\right)\]</span></p>
<div class="fragment">
<p>In this case <span class="math inline">\(\delta_{2020}^y =0.8075 = 80.75%\)</span>.</p>
<blockquote>
<p>Interpretation: Between and 2019, the price for Apple <em>increased</em> 80.75%.</p>
</blockquote>
</div>
</section>
<section id="growth-rates-1" class="slide level2">
<h2>Growth Rates</h2>
<p>More generally <span class="math display">\[\delta_{t+k|t}=\frac{y_{t+k}-y_t}{y_t}\]</span></p>
<p>Or <span class="math display">\[y_{t+k}=y_t(1+\delta_{t+k|t})\]</span></p>
<p><small>(homework: Show step by step how you go from one to the other.)</small></p>
<blockquote>
<p>Note: In this case <span class="math inline">\(\delta_{t+k|t}\)</span> is what percentage the variable changed from <span class="math inline">\(t\)</span> to <span class="math inline">\(t+k\)</span>, and <span class="math inline">\(k\)</span> is the number of periods.</p>
</blockquote>
</section>
<section id="example-1" class="slide level2">
<h2>Example</h2>
<p>We had <span class="math inline">\(y_{2019}=73.41\)</span>, and <span class="math inline">\(y_{2023} =192.53\)</span>. We will try to find <span class="math inline">\(\delta_{2023|2019}^y\)</span></p>
<ul>
<li class="fragment">What is the value of <span class="math inline">\(k\)</span> in this case?</li>
</ul>
<div class="fragment">
<p><span class="math display">\[k=2023-2019=4\]</span></p>
<ul>
<li class="fragment">What is the growth rate between <span class="math inline">\(2019\)</span> and <span class="math inline">\(2023\)</span>?</li>
</ul>
</div>
<div class="fragment">
<p><span class="math display">\[\delta_{2023|2019}^y = \frac{192.53 - 73.41}{73.41} = 1.6227 = 162.27\%\]</span></p>
<blockquote>
<p>For Apple, the stock price grew 162.27% between 2019 and 2023, or the stock price for Apple in 2023 is 162.27% larger than in 2019.</p>
</blockquote>
</div>
</section>
<section id="growth-rates-2" class="slide level2">
<h2>Growth Rates</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Warning</strong></p>
</div>
<div class="callout-content">
<p>You should be careful with your interpretation and use of this <em>cumulative</em> growth rate, because it <strong>does not</strong> mean that <span class="math inline">\(y\)</span> grew <span class="math inline">\(\delta_{t+k|t}^y\)</span> <strong>per period</strong> between <span class="math inline">\(t\)</span> and <span class="math inline">\(t+k\)</span>.</p>
</div>
</div>
</div>
<div class="fragment">
<p><br>
</p>
<div class="callout callout-note no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Average Growth Rate</strong></p>
</div>
<div class="callout-content">
<p>Let <span class="math inline">\(y_t\)</span> be a variable that might take different values over time. The <strong>average growth rate</strong> betweek <span class="math inline">\(t\)</span> and <span class="math inline">\(t+k\)</span> is given by <span class="math inline">\(\overline{\delta}_{t+k|t}^y\)</span>, and takes a value such that:</p>
<p><span class="math display">\[y_{t+k}=y_t\left(1+\overline{\delta}_{t+k|t}\right)^k\]</span></p>
<p><small>I dropped <span class="math inline">\(y\)</span> from the notation in the formula because it is obvious that we are talking about the variable <span class="math inline">\(y\)</span>.</small></p>
</div>
</div>
</div>
</div>
</section>
<section id="growth-rates-3" class="slide level2">
<h2>Growth Rates</h2>
<p>Let’s start with <span class="math inline">\(y_t\)</span>… and the traditional growth rates <span class="math inline">\(\delta_t\)</span>:</p>
<p><span class="math display">\[y_{t+1} = y_t(1+\delta_t)\]</span></p>
<p><span class="math display">\[y_{t+2} = y_{t+1}(1+\delta_{t+1})\]</span></p>
<p><span class="math display">\[y_{t+3} = y_{t+1}(1+\delta_{t+2})\]</span></p>
<p>Can we write <span class="math inline">\(y_{t+2}\)</span> as a function of <span class="math inline">\(y_t\)</span>?</p>
<div class="fragment">
<p><span class="math display">\[y_{t+2} = y_{t+1}(1+\delta_{t+1}) = y_{t}(1+\delta_t)(1+\delta_{t+1})\]</span></p>
</div>
<div class="fragment">
<p>And <span class="math inline">\(y_{t+3}\)</span>?</p>
</div>
<div class="fragment">
<p><span class="math display">\[y_{t+3} = y_{t}(1+\delta_t)(1+\delta_{t+1})(1+\delta_{t+2})\]</span></p>
</div>
</section>
<section id="growth-rates-4" class="slide level2">
<h2>Growth Rates</h2>
<p>Generalizing</p>
<p><span class="math display">\[y_{t+k}=y_t (1+\delta_t)(1+\delta_{t+1})...(1+\delta_{t+k-1})\]</span></p>
<p>When computing the average growth rate, we are trying to find <span class="math inline">\(\overline{\delta}\)</span> such that if the growth rate was the same every period, it would have taken <span class="math inline">\(y_t\)</span> to the value of <span class="math inline">\(y_{t+k}\)</span> all the same:</p>
<p><span class="math display">\[y_{t+k}=y_t(1+\overline{\delta})(1+\overline{\delta})...(1+\overline{\delta})\]</span></p>
<div class="fragment">
<p>How many times is <span class="math inline">\((1+\overline{\delta})\)</span> multiplied in the expression?</p>
</div>
</section>
<section id="growth-rates-5" class="slide level2">
<h2>Growth Rates</h2>
<p><span class="math display">\[y_{t+k} = y_t \left(1+\overline{\delta}\right)^k\]</span></p>
<div class="fragment">
<p><span class="math display">\[\frac{y_{t+k}}{y_t} = \left(1+\overline{\delta}\right)^k\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[\left(\frac{y_{t+k}}{y_t}\right)^{1/k} = \left(1+\overline{\delta}\right)\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[\left(\frac{y_{t+k}}{y_t}\right)^{1/k} - 1 = \overline{\delta}\]</span></p>
<p><span class="math display">\[\overline{\delta}_{t+k|t}=\left(\frac{y_{t+k}}{y_t}\right)^{1/k} - 1\]</span></p>
</div>
</section>
<section id="example-2" class="slide level2">
<h2>Example</h2>
<p>We had <span class="math display">\[\delta_{2023|2019}^y = \frac{192.53 - 73.41}{73.41} = 1.6227 = 162.27\%\]</span></p>
<p>But what now is the <strong>average growth rate</strong> between 2019 and 2023?</p>
<div class="fragment">
<p>Remember <span class="math inline">\(k = 4\)</span></p>
<p><span class="math display">\[
\overline{\delta} =
\left(\frac{192.53}{73.41}\right)^{1/4} - 1
\approx 0.2726=
27.26\%
\]</span></p>
<blockquote>
<p>Interpretation: On average, between 2019 and 2022 <span class="math inline">\(y\)</span> grew 27.26% every year.</p>
</blockquote>
</div>
</section>
<section id="example-3" class="slide level2">
<h2>Example</h2>
<p>Note that <span class="math display">\[
(1+27.26\%)^4 =
(1+0.2726)^4 \approx
2.6227\approx
1 + 162.27\%
\]</span></p>
</section></section>
<section>
<section id="index-numbers---introduction-and-simple-index-numbers" class="title-slide slide level1 center">
<h1>Index Numbers - Introduction and Simple Index Numbers</h1>

</section>
<section id="motivation" class="slide level2">
<h2>Motivation</h2>

<img data-src="1_intro_files/figure-revealjs/unnamed-chunk-4-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p>Which stock would you have purchased in 2015-08-12?</p>
</section>
<section id="motivation-1" class="slide level2">
<h2>Motivation</h2>
<p>What’s the important question here?</p>
<div class="fragment">
<p>Which one grew more! For this, levels are not as relevant as their evolution over time.</p>
<p>For example, say we have prices for two stocks A and B. Say we want to hold these stocks for only one period, which one would choose to invest your hard earned <span class="emoji" data-emoji="dollar">💵</span>?</p>
</div>
<div class="fragment">
<p>How many stocks will you be able to buy of each stock, if their prices are <span class="math inline">\(a_t\)</span> and <span class="math inline">\(b_t\)</span>, and you have US$1000?</p>
</div>
<div class="fragment">
<p><span class="math inline">\(n_a=\frac{1000}{a_t}\)</span> of stock A and <span class="math inline">\(n_b=\frac{1000}{b_t}\)</span> of stock <span class="math inline">\(B\)</span>. Note that <span class="math inline">\(n_a\)</span> and <span class="math inline">\(n_b\)</span> are the amount of stock you can buy of each.</p>
</div>
</section>
<section id="motivation-2" class="slide level2">
<h2>Motivation</h2>
<p>Now is a new day <span class="emoji" data-emoji="sunrise_over_mountains">🌄</span>! Prices are now <span class="math inline">\(a_{t+1}\)</span> and <span class="math inline">\(b_{t+1}\)</span>, how much is your portfolio worth today?</p>
<div class="fragment">
<ol type="1">
<li class="fragment"><p>If you bought stock A: <span class="math inline">\(a_{t+1} n_a = a_{t+1}\frac{1000}{a_t}\)</span></p></li>
<li class="fragment"><p>If you bought stock B: <span class="math inline">\(b_{t+1} n_b = b_{t+1}\frac{1000}{b_t}\)</span></p></li>
</ol>
</div>
<div class="fragment">
<p>Note that the 1000 is fixed, so it is just what we invested, it is not going to change anything in our decision on buying A vs B, what is really important is <span class="math inline">\(\frac{a_{t+1}}{a_t}\)</span> and <span class="math inline">\(\frac{b_{t+1}}{b_t}\)</span>, that is the growth rate of prices for each stock, as</p>
<p><span class="math display">\[\frac{a_{t+1}}{a_t}=1+\delta_{t+1}^a \quad\text{and}\quad \frac{b_{t+1}}{b_t}=1+\delta_{t+1}^b\]</span></p>
</div>
</section>
<section id="motivation-3" class="slide level2">
<h2>Motivation</h2>
<p>You did not sell and…</p>
<p>Now is (another) new day <span class="emoji" data-emoji="sunrise_over_mountains">🌄</span>! Prices are now <span class="math inline">\(a_{t+2}\)</span> and <span class="math inline">\(b_{t+2}\)</span>, how much is your portfolio worth today?</p>
<div class="fragment">
<ol type="1">
<li class="fragment"><p>If you bought stock A: <span class="math inline">\(a_{t+2} n_a = a_{t+2}\frac{1000}{a_t}\)</span></p></li>
<li class="fragment"><p>If you bought stock B: <span class="math inline">\(b_{t+2} n_b = b_{t+2}\frac{1000}{b_t}\)</span></p></li>
</ol>
</div>
<div class="fragment">
<p>blah, blah…</p>
<p><span class="math display">\[\frac{a_{t+2}}{a_t}=1+\delta_{t+2}^a \quad\text{and}\quad \frac{b_{t+2}}{b_t}=1+\delta_{t+2}^b\]</span></p>
<p>If we wait two days, we only care how is the price today compared to when we made the purchase. We could make instead a plot of <span class="math inline">\(1+\delta_{t+k}\)</span> to see which grew more!</p>
</div>
</section>
<section id="motivation-4" class="slide level2">
<h2>Motivation</h2>

<img data-src="1_intro_files/figure-revealjs/unnamed-chunk-5-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"><p>Now we have a much clear picture. We can compare their evolution starting in 2015-08-12.</p>
<p>What can you read from the plot?</p>
</section>
<section id="motivation-5" class="slide level2">
<h2>Motivation</h2>
<p>Note that for 2015-08-12, we would have, for A and B:</p>
<p><span class="math display">\[1+\frac{a_t-a_t}{a_t}=1\quad\text{and}\quad 1+\frac{b_t-b_t}{b_t}=1\]</span></p>
<p>We just built and index number!</p>
<p>By convention though, instead of using 1 for the reference date, we will use 100 (as in 100%) for the reference day (we will put a name to this in a few moments).</p>
<p><br>
</p>
<p>When our new series was 2, we understood that <span class="math inline">\(1+\delta_{t+k}=2\)</span> or <span class="math inline">\(\delta_{t+k}=1\)</span>, <em>i.e.</em> the price grew 100%, or <em>doubled</em>! Now, with the new notation, we would have that the new series would take the value of 200, <em>i.e.</em> the price is now 200% the value it had at our initial date.</p>
</section>
<section id="index-numbers" class="slide level2">
<h2>Index Numbers</h2>
<div class="callout callout-note no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Index Number</strong></p>
</div>
<div class="callout-content">
<p>An <strong>Index Number</strong> is a scaled variable that takes as a reference point the value an underlying variable took at a fixed point in time. Say, for an underlying variable <span class="math inline">\(x_t\)</span> we build an index <span class="math inline">\(I_t\)</span>.</p>
<p><span class="math display">\[I_t=\frac{x_t}{x_0}\times 100\]</span></p>
<p>Where <span class="math inline">\(x_t\)</span> is the value the underlying variable takes at time <span class="math inline">\(t\)</span>, and <span class="math inline">\(x_0\)</span> represents the value this variable took at our reference point. This period is called <strong>base</strong>.</p>
<blockquote>
<p>Note: In this case we used time as the dimension for <span class="math inline">\(t\)</span> but this needs not be the case, we will see examples later.</p>
</blockquote>
</div>
</div>
</div>
<p><br>
</p>
<p>In our previous example, the base day would have been 2015-08-12. Note that in the base period <span class="math display">\[I_0=\frac{x_0}{x_0}\times 100 = 100\]</span></p>
</section>
<section id="index-numbers-1" class="slide level2">
<h2>Index Numbers</h2>
<p>Index Numbers are defined by their underlying variable. This can change over time, or it can change according to another dimension, like geography, or both! We will see examples.</p>
<p>Also, an Index Number can have a fixed base or a moving base.</p>
<div class="cell">
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-8a4e38fb1b687f2b1193" style="width:960px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-8a4e38fb1b687f2b1193">{"x":{"diagram":"\ndigraph TimeSeriesStructure {\n  graph [layout = dot, rankdir = TB]\n\n  node [shape = box, style = filled, fillcolor = lightgray, fontname = Helvetica]\n\n  Index [label = \"Index\"]\n  UnderlyingVariable [label = \"Underlying Variable\"]\n  Base [label = \"Base\"]\n  Dimension [label = \"Dimension\"]\n\n  Simple [label = \"Simple\"]\n  Composite [label = \"Composite\"]\n\n  Fixed [label = \"Fixed\"]\n  Rolling [label = \"Rolling\"]\n\n  Chronological [label = \"Chronological\"]\n  Geographical [label = \"Geographical\"]\n\n  Index -> UnderlyingVariable\n  Index -> Base\n  Index -> Dimension\n\n  UnderlyingVariable -> Simple\n  UnderlyingVariable -> Composite\n\n  Base -> Fixed\n  Base -> Rolling\n\n  Dimension -> Chronological\n  Dimension -> Geographical\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="index-numbers-2" class="slide level2">
<h2>Index Numbers</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Index Numbers</strong></p>
</div>
<div class="callout-content">
<ul>
<li class="fragment">Simple and Composite are mutually exclusive</li>
<li class="fragment">Fixed and Moving are mutually exclusive</li>
<li class="fragment">Rolling always needs a chronological dimension</li>
</ul>
</div>
</div>
</div>
</section>
<section id="examples" class="slide level2">
<h2>Examples</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Type</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Simple</td>
<td>Single stock price</td>
</tr>
<tr class="even">
<td>Composite</td>
<td>SP500 (market index), CPI</td>
</tr>
<tr class="odd">
<td>Fixed Base</td>
<td>GDP, CPI, market index</td>
</tr>
<tr class="even">
<td>Rolling Base</td>
<td>Some measures of GDP, Commodities Futures</td>
</tr>
<tr class="odd">
<td>Chronological</td>
<td>Stock price over time, CPI, GDP</td>
</tr>
<tr class="even">
<td>Geographical</td>
<td>BigMac Index</td>
</tr>
</tbody>
</table>
</section>
<section id="index-numbers-4" class="slide level2">
<h2>Index Numbers</h2>
<p>Importantly, an index number is <em>no bueno</em> to reflect the level of a variable, but its evolution or relative value against a base.</p>
</section>
<section id="rolling-base" class="slide level2">
<h2>Rolling Base</h2>
<div class="callout callout-note no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Chain or Link Index</strong></p>
</div>
<div class="callout-content">
<p>A <strong>Chain or Link Index Number</strong> is an index number that updates its base in every period.</p>
<p><span class="math display">\[I_t = \frac{x_t}{x_{t-1}}\times 100\]</span></p>
<blockquote>
<p>Interpretation: It tells you how much the variable increased compared to the <strong>previous</strong> period.</p>
</blockquote>
</div>
</div>
</div>
</section>
<section id="index-numbers-5" class="slide level2">
<h2>Index Numbers</h2>
<p>Index numbers allow us to easily compute the growth rate between any two periods, just like we would do with the underlying variable:</p>
<ol type="1">
<li class="fragment">Simple Index Number</li>
</ol>
<div class="fragment">
<p><span class="math display">\[1+\delta_{t+k,t}=\frac{x_{t+k}}{x_t}=\frac{x_{t+k}}{x_t}=\frac{\frac{x_{t+k}}{x_0}}{\frac{x_t}{x_0}}=\frac{I_{t+k}}{I_t}\]</span></p>
<ol start="2" type="1">
<li class="fragment">Chain Index Number</li>
</ol>
</div>
<div class="fragment">
<p><small></small></p><small>
<p><span class="math display">\[1+\delta_{t+k,t}=\frac{x_{t+k}}{x_t}=\frac{x_{t+k}}{x_{t+k-1}}\frac{x_{t+k-1}}{x_{t}}=\frac{x_{t+k}}{x_{t+k-1}}\frac{x_{t+k-1}}{x_{t+k-2}}\frac{x_{t+k-2}}{x_{t}}=\frac{x_{t+k}}{x_{t+k-1}}\frac{x_{t+k-1}}{x_{t+k-2}}...\frac{x_{t+1}}{x_{t}}\]</span></p>
<p><span class="math display">\[1+\delta_{t+k,t}=I_{t+k}\times I_{t+k-1}\times ... \times I_{t+2} \times I_{t+1}\]</span></p>
</small><p><small></small></p>
</div>
</section>
<section id="index-numbers-6" class="slide level2">
<h2>Index Numbers</h2>
<div class="callout callout-warning callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Do not use 100 index when multiplying chain or link indices, use the decimal notation.</strong></p>
</div>
<div class="callout-content">
<p>Note that if the underlying variable does not change at all, you should expect the same value, <span class="math inline">\(x_t=x_{t+1}=x_{t+2}\)</span></p>
<p>In this case <span class="math inline">\(I_{t+1}=\frac{x_{t+1}}{x_t}=1\)</span> and <span class="math inline">\(I_{t+2}=\frac{x_{t+2}}{x_{t+1}}=1\)</span>, and therefore <span class="math display">\[1+\delta_{t+2,t}=1\times 1= 1\]</span></p>
<p>This is the correct way to do it <span class="emoji" data-emoji="white_check_mark">✅</span>.</p>
<p>But if instead you used the 100 to multiply: <span class="math display">\[1+\delta_{t+2,t}=100\times 100= 10000\]</span> and we get that <span class="math inline">\(x\)</span> grew 100 times! (<span class="emoji" data-emoji="x">❌</span> because we know that <span class="math inline">\(x_t=x_{t+1}=x_{t+2}\)</span>)</p>
</div>
</div>
</div>
</section>
<section id="index-numbers-7" class="slide level2">
<h2>Index Numbers</h2>
<p>We can always transform a chain index number into a fixed base index number.</p>
<ol type="1">
<li class="fragment"><p>Chose a reference, for example for period 3.</p></li>
<li class="fragment"><p>Remember: what you want to achieve: <span class="math inline">\(\forall t, I'_t=\frac{x_t}{x_3}\)</span></p></li>
<li class="fragment"><p>Remember: that we have <span class="math inline">\(I_t=\frac{x_t}{x_{t-1}}\)</span></p></li>
<li class="fragment"><p>Use what we did just before:</p></li>
</ol>
<div class="fragment">
<p><span class="math display">\[ I_t' = I_t I_{t-1} ...I_{4} = \frac{x_t}{x_{t-1}}\frac{x_{t-1}}{x_{t-2}}...\frac{x_4}{x_3}=\frac{x_t}{x_3}=I'_t\]</span></p>
</div>
</section>
<section id="example-4" class="slide level2">
<h2>Example</h2>
<p><small></small></p><small>
<p>Suppose we want to convert this Chain Index into Fix Base index, with the base year in 2020. This will be our 100.</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">2020</th>
<th style="text-align: center;">2021</th>
<th style="text-align: center;">2022</th>
<th style="text-align: center;">2023</th>
<th style="text-align: center;">2024</th>
<th style="text-align: center;">2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Price</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">34</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">39</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\frac{34}{30} 100\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{37}{34} 100\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{35}{37} 100\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{36}{35} 100\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{39}{36} 100\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(I_{chain}\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">113.3</td>
<td style="text-align: center;">108.8</td>
<td style="text-align: center;">94.6</td>
<td style="text-align: center;">97.1</td>
<td style="text-align: center;">108.3</td>
</tr>
<tr class="even">
<td></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(100\frac{113.3}{100}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(113.3\frac{108.8}{100}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(123.3\frac{94.6}{100}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(116.7 \frac{97.1}{100}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(120\frac{108.3}{100}\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(I_{t|2020}\)</span></td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">113.3</td>
<td style="text-align: center;">123.3</td>
<td style="text-align: center;">116.7</td>
<td style="text-align: center;">120</td>
<td style="text-align: center;">130</td>
</tr>
</tbody>
</table>
<p>Note that, for example in 2024, we have <span class="math inline">\(I_{2024|2020}=116.7\)</span>, which was computed as <span class="math inline">\(123.3\times\frac{94.6}{100}\)</span>. But <span class="math inline">\(123.3\)</span> was the base 2020 index of the previous period, which in turn was computed as <span class="math inline">\(113.3\frac{108.8}{100}\)</span>, so in reality:</p>
<p><span class="math display">\[116.7=123.3\frac{94.6}{100}=113.3\frac{108.8}{100}\frac{94.6}{100}=100\frac{113.3}{100}\frac{108.8}{100}\frac{94.6}{100}\]</span></p>
<p>If you pay attention, wou will see that we have there the product of the <em>chain Index</em> in 2021, 2022, and 2023. We divided by 100 because, to multiply, we need to divide by 100 before.</p>
</small><p><small></small></p>
</section>
<section id="base-change" class="slide level2">
<h2>Base Change</h2>
<p>In case we have the data, we just need to compute the Index with the base that we want, however, if we do not have the data, and we just have a Fix Base index, we can do it all the same!</p>
<p>Say we have an index with base 0. Maybe we want to change it to base 2.</p>
</section>
<section id="base-change-1" class="slide level2">
<h2>Base Change</h2>
<div id="tbl-panel" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-tbl">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-panel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Changing Base
</figcaption>
<div aria-describedby="tbl-panel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top">
<caption>Base 0</caption>
<thead>
<tr class="header">
<th style="text-align: left;">period</th>
<th style="text-align: left;">Index</th>
<th style="text-align: left;">Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: left;"><span class="math inline">\(I_{0|0}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{x_0}{x_0}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;"><span class="math inline">\(I_{1|0}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{x_1}{x_0}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;"><span class="math inline">\(I_{2|0}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{x_2}{x_0}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;"><span class="math inline">\(I_{3|0}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{x_3}{x_0}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">…</td>
<td style="text-align: left;">…</td>
<td style="text-align: left;">…</td>
</tr>
<tr class="even">
<td style="text-align: left;">t</td>
<td style="text-align: left;"><span class="math inline">\(I_{t|0}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{x_t}{x_0}\)</span></td>
</tr>
</tbody>
</table>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<table class="caption-top">
<caption>Base 2</caption>
<thead>
<tr class="header">
<th style="text-align: left;">period</th>
<th style="text-align: left;">Index</th>
<th style="text-align: left;">Formula</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: left;"><span class="math inline">\(I_{0|2}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{x_0}{x_2}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;"><span class="math inline">\(I_{1|2}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{x_1}{x_2}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;"><span class="math inline">\(I_{2|2}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{x_2}{x_2}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;"><span class="math inline">\(I_{3|2}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{x_3}{x_2}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">…</td>
<td style="text-align: left;">…</td>
<td style="text-align: left;">…</td>
</tr>
<tr class="even">
<td style="text-align: left;">t</td>
<td style="text-align: left;"><span class="math inline">\(I_{t|2}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\frac{x_t}{x_2}\)</span></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</figure>
</div>
</section>
<section id="base-change-2" class="slide level2">
<h2>Base Change</h2>
<p>But how can we transform them, if we do not know <span class="math inline">\(x_i\)</span> <span class="math inline">\(\forall i\)</span>?</p>
<div class="fragment">
<p><span class="math display">\[I_{t|2}=\frac{x_t}{x_2}=1\frac{x_t}{x_2}=\frac{1/x_0}{1/x_0}\frac{x_t}{x_2}=\frac{\frac{x_t}{x_0}}{\frac{x_2}{x_0}}=\frac{I_{t|0}}{I_{2|0}}\]</span></p>
<p>And that is how we can re-base an index without knowing the value for the underlying variable (<span class="math inline">\(x_t\)</span>)!</p>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Mixing up stuff</strong></p>
</div>
<div class="callout-content">
<p>Previously we covered how to go from a chain index to a fixed base one. Now we saw how to change the base of a fixed base index. With both things together you can turn a chain index into fixed base one, with base you want!</p>
</div>
</div>
</div>
</div>
</section>
<section id="example-5" class="slide level2">
<h2>Example</h2>
<table class="caption-top" style="width:100%;">
<caption>Stock prices</caption>
<colgroup>
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">2020</th>
<th style="text-align: center;">2021</th>
<th style="text-align: center;">2022</th>
<th style="text-align: center;">2023</th>
<th style="text-align: center;">2024</th>
<th style="text-align: center;">2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Price</td>
<td style="text-align: center;">30</td>
<td style="text-align: center;">34</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">35</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">39</td>
</tr>
<tr class="even">
<td><span class="math inline">\(I_{t|2020}\)</span></td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">113.3</td>
<td style="text-align: center;">123.3</td>
<td style="text-align: center;">116.7</td>
<td style="text-align: center;">120</td>
<td style="text-align: center;">130</td>
</tr>
<tr class="odd">
<td></td>
<td style="text-align: center;"><span class="math inline">\(\frac{100}{123.3}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{113.3}{123.3}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{123.3}{123.3}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{116.7}{123.3}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{120.0}{123.3}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\frac{130.0}{123.3}\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(I_{t|2022}\)</span></td>
<td style="text-align: center;">81.1</td>
<td style="text-align: center;">91.9</td>
<td style="text-align: center;">100</td>
<td style="text-align: center;">94.6</td>
<td style="text-align: center;">97.3</td>
<td style="text-align: center;">105.4</td>
</tr>
</tbody>
</table>
<blockquote>
<p>New information? Yes! For example, without any computation we know that the price in 2025 was 30% larger than in 2020, and 5.4% larger than in 2022</p>
</blockquote>
</section>
<section id="tests-for-good-simple-index-numbers" class="slide level2">
<h2>Tests for good Simple Index Numbers</h2>
<p>We can test the properties for Simple Index Numbers. These represent desirable properties for good index numbers.</p>
<ol type="1">
<li class="fragment"><strong>Identity test:</strong> If the variable in the current period is the same as in the base period, the index should be 1 (or 100). Of course this implies <span class="math display">\[I_{0|0}=1\]</span>.</li>
<li class="fragment"><strong>Proportionality test:</strong> If the variable increases by <span class="math inline">\(k\)</span>, the index should increase by <span class="math inline">\(k\)</span>. <span class="math display">\[x_t=kx_0\ \Rightarrow\ i_{t|0}=k\]</span></li>
</ol>
</section>
<section id="factor-reversal" class="slide level2">
<h2>Tests for good Simple Index Numbers</h2>
<ol start="3" type="1">
<li class="fragment"><strong>Time Reversal test:</strong> If you exchange the base between two periods, then the index in one base, should be the inverse of the other: <span class="math display">\[i_{t|0}=\frac{1}{i{0|t}}\ \Leftrightarrow\ i_{t|0}i_{0|t}=1\]</span></li>
<li class="fragment"><strong>Factor Reversal test:</strong> If we have two index numbers, one for variable <span class="math inline">\(x\)</span> and another for <span class="math inline">\(y\)</span>, then if <span class="math inline">\(z=x\times y\)</span> we should have <span class="math display">\[i_{t|0}^z=i_{t|0}^x\times i_{t|0}^y\]</span></li>
</ol>
</section>
<section id="tests-for-good-simple-index-numbers-1" class="slide level2">
<h2>Tests for good Simple Index Numbers</h2>
<ol start="5" type="1">
<li class="fragment"><p><strong>Circularity test:</strong> The index at <span class="math inline">\(t\)</span> base <span class="math inline">\(0\)</span> should be the product of all the link index numbers up to <span class="math inline">\(t\)</span>, <span class="math display">\[i_{t|0}=i_{t|t-1}\times i_{t-1|t-2}...i_{2|1}\times i_{1|0}\]</span> This formalizes the relationship between fixed base and chain index numbers.</p></li>
<li class="fragment"><p><strong>Homogeneity test:</strong> If the variable, for every <span class="math inline">\(t\)</span> is multiplied by a constant, the index should not be affected.</p></li>
</ol>
</section>
<section id="tests-for-good-simple-index-numbers-2" class="slide level2">
<h2>Tests for good Simple Index Numbers</h2>
<ol start="7" type="1">
<li class="fragment"><strong>Well-definedness:</strong> The index number must be meaningful, and as prices and quantities usually are larger than zero, index numbers must be positive. Even further, a good index number should not take the value of <span class="math inline">\(\infty\)</span>.</li>
</ol>
<div class="fragment">
<p>Ask yourself, what information are you getting here?</p>
</div>
<div class="fragment">
<p>A value of <span class="math inline">\(0\)</span> might also be problematic, although it is not totally meaningless. The problem arises when you want to deal with chain index numbers, where a <span class="math inline">\(0\)</span> would indeterminate the rest of the chain. Also, you could never use as a base period, a period where the variable took the value of <span class="math inline">\(0\)</span>.</p>
</div>
</section></section>
<section>
<section id="index-numbers-composite-index-numbers" class="title-slide slide level1 center">
<h1>Index Numbers: Composite Index Numbers</h1>

</section>
<section id="composite-index-numbers" class="slide level2">
<h2>Composite Index Numbers</h2>
<div class="callout callout-note no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Composite Index Numbers (a.k.a. Aggregate Index Numbers)</strong></p>
</div>
<div class="callout-content">
<p><strong>Composite Index Numbers</strong> are index numbers that have more than a single underlying variable, or which underlying variable is computed itself as a combination of other variables.</p>
<p>A composite index tracks the combined evolution of multiple phenomena at the same time. It summarizes how a diverse group of elements changes over time.</p>
<p>Example: The performance of a class, measured by the average grade. The average is computed with each individual grade, and therefore if we make an index based on the average of the class, we would have a composite index number.</p>
</div>
</div>
</div>
</section>
<section id="composite-index-numbers-1" class="slide level2">
<h2>Composite Index Numbers</h2>
<p>This is a great opportunity to introduce another classification for our index numbers:</p>
<div class="cell">
<div class="cell-output-display">
<div class="grViz html-widget html-fill-item" id="htmlwidget-ce09373bd9ae3af198ff" style="width:960px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-ce09373bd9ae3af198ff">{"x":{"diagram":"\ndigraph flowchart {\n  graph [layout = dot, rankdir = TB]\n  node [shape = box, style = filled, fillcolor = lightgray, fontname = Helvetica]\n\n  A [label = \"Index\"]\n  B [label = <Price <i>P<\/i>>]\n  C [label = <Quantity <i>Q<\/i>>]\n  D [label = <Value <i>P<\/i> <i>&times;<\/i> <i>Q<\/i>>]\n\n  A -> B\n  A -> C\n  A -> D\n}\n","config":{"engine":"dot","options":null}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="composite-index-numbers-2" class="slide level2">
<h2>Composite Index Numbers</h2>
<p>Typically, values are collected in nominal terms, <em>i.e.</em> <strong>current prices</strong>, which is a <em>value</em>.</p>
<p><span class="math display">\[v_t=p_t\times q_t\]</span></p>
<div class="fragment">
<p>Note that, if <span class="math inline">\(\delta_{t+1}^v\)</span> is the growth rate of <span class="math inline">\(v_t\)</span>:</p>
<p><span class="math display">\[v_{t+1} = v_t\left(1+\delta_{t+1}^v\right)\]</span></p>
<p>and obviously, it is also true that:</p>
<p><span class="math display">\[v_{t+1} = p_{t+1}\times q_{t+1}\]</span></p>
</div>
</section>
<section id="composite-index-numbers-3" class="slide level2">
<h2>Composite Index Numbers</h2>
<p>But if we let <span class="math inline">\(\delta_{t+1}^p\)</span> be the growth rate of prices, and <span class="math inline">\(\delta_{t+1}^p\)</span> the growth rate of quantities we can rewrite <span class="math inline">\(v_{t+1}\)</span> as:</p>
<p><span class="math display">\[v_{t+1}=p_t\left(1+\delta_{t+1}^p\right)q_t\left(1+\delta_{t+1}^q\right)\]</span></p>
<div class="fragment">
<p><span class="math display">\[v_{t+1} = p_tq_t(1+\delta_{t+1}^p)(1+\delta_{t+1}^q)\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[v_{t+1} = v_t(1+\delta_{t+1}^p)(1+\delta_{t+1}^q)\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[v_{t}(1+\delta_{t+1}^v) = v_t(1+\delta_{t+1}^p)(1+\delta_{t+1}^q)\]</span></p>
</div>
</section>
<section id="section" class="slide level2 big-emoji">
<h2></h2>
<p><span class="emoji" data-emoji="bulb">💡</span></p>
<style>
.big-emoji {
  font-size: 10em;
  text-align: center;
  vertical-align: middle;
}
</style>
</section>
<section id="composite-index-numbers-4" class="slide level2">
<h2>Composite Index Numbers</h2>
<p><span class="math display">\[(1+\delta_{t+1}^v) = (1+\delta_{t+1}^p)(1+\delta_{t+1}^q)\]</span></p>
<p><span class="math inline">\(\delta_t^v\)</span> is what we call <strong>nominal change rate</strong>, while <span class="math inline">\(\delta_t^q\)</span> is what we call <strong>real change rate</strong>. We can find out the real change rate (<span class="math inline">\(\delta^q\)</span>), if we know the nominal change rate (<span class="math inline">\(\delta^v\)</span>), and the prices change rate (<span class="math inline">\(\delta^p\)</span>):</p>
<p><span class="math display">\[\left(1+\delta_{t}^q\right) = \frac{\left(1+\delta_t^v\right)}{\left(1+\delta_t^p\right)}\]</span> <span class="math display">\[\delta_{t}^q = \frac{\left(1+\delta_t^v\right)}{\left(1+\delta_t^p\right)}-1\]</span></p>
</section>
<section id="composite-index-numbers-5" class="slide level2">
<h2>Composite Index Numbers</h2>
<p>Suppose we have index numbers for <span class="math inline">\(v\)</span>, <span class="math inline">\(q\)</span>, and <span class="math inline">\(p\)</span>, all with base <span class="math inline">\(b\)</span> (remember you can re-base your index numbers easily if they do not share the same base).</p>
<p><span class="math display">\[I_{t|b}^q = \frac{I_{t|b}^v}{I_{t|b}^p}\]</span></p>
<div class="fragment">
<p><span class="math display">\[\frac{q_t}{q_b} = \frac{\frac{v_t}{v_b}}{\frac{p_t}{p_b}}\]</span> <span class="math display">\[\frac{q_t}{q_b} = \frac{\frac{p_tq_t}{p_bq_b}}{\frac{p_t}{p_b}}=\frac{p_tq_t}{p_bq_b}\frac{p_b}{p_t}=\frac{q_t}{q_b}\]</span></p>
</div>
</section>
<section id="example-6" class="slide level2">
<h2>Example</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>2021</th>
<th>2022</th>
<th>2023</th>
<th>2024</th>
<th>2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sales Index</td>
<td>99</td>
<td>100</td>
<td>107</td>
<td>110</td>
<td>111</td>
</tr>
<tr class="even">
<td>Price Index</td>
<td>95</td>
<td>100</td>
<td>102</td>
<td>106</td>
<td>109</td>
</tr>
</tbody>
</table>
<p>Let’s find the quantities index, with base 2022. Immediately we can fix <span class="math inline">\(i_{t|b}^q=100\)</span>.</p>
<p><span class="math display">\[I_{2021}^q=\frac{I_{2021}^v}{I_{2021}^p}=\frac{99}{95}=1.04\]</span></p>
<div class="fragment">
<p>Then <span class="math inline">\(I_{2021} = 104\)</span>, quantities decreased from 2021 to 2022!</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>2021</th>
<th>2022</th>
<th>2023</th>
<th>2024</th>
<th>2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Quantities Index</td>
<td>104.21</td>
<td>100</td>
<td>104.9</td>
<td>103.77</td>
<td>101.83</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="example-7" class="slide level2">
<h2>Example</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>2021</th>
<th>2022</th>
<th>2023</th>
<th>2024</th>
<th>2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Quantities Index</td>
<td>104.21</td>
<td>100</td>
<td>104.9</td>
<td>103.77</td>
<td>101.83</td>
</tr>
</tbody>
</table>
<p>Now we can compute what was the real change rate between 2024 and 2025:</p>
<div class="fragment">
<p><span class="math display">\[\delta_{2025}=\frac{102}{104}-1=-0.0187=-1.87\%\]</span></p>
<blockquote>
<p>Real sales decreased 1.87% from 2024 to 2025.</p>
</blockquote>
</div>
</section>
<section id="example-8" class="slide level2">
<h2>Example</h2>
<p>Let’s check:</p>
<p><span class="math display">\[\delta_{2025}^q=\frac{(1+\delta_{2025}^v)}{(1+\delta_{2025}^p)}-1=\frac{111/110}{109/106}-1=0.9813-1\]</span> <span class="math display">\[\delta_{2025}^q=-0.0187=-1.87\%\]</span></p>
</section>
<section id="baskets" class="slide level2">
<h2>Baskets</h2>
<div class="callout callout-note no-icon callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<p><strong>Basket 🧺</strong></p>
</div>
<div class="callout-content">
<p><strong>Basket</strong> are sets of goods, which are used to track the evolution of, for example, a price level.</p>
<p>In economics, we often use price and quantity index numbers to measure how the prices or quantities of a set of goods (a <strong>basket</strong>) change over time.</p>
</div>
</div>
</div>
<div class="fragment">
<blockquote>
<p>A very important question: What are the weights that the different goods should have in the basket?</p>
</blockquote>
</div>
</section>
<section id="aggregate-index-numbers" class="slide level2">
<h2>Aggregate Index Numbers</h2>
<p>From the family of formulas to create weighted composite index numbers, we will focus on the two most common:</p>
<ol type="1">
<li class="fragment"><p><strong>Laspeyres</strong>: uses base-period quantities (prices) as weights.</p></li>
<li class="fragment"><p><strong>Paasche</strong>: uses current-period quantities (prices) as weights.</p></li>
</ol>
<div class="fragment">
<p>These are used to measure the evolution of <em>prices (quantities)</em>.</p>
</div>
</section>
<section id="kids-explanation" class="slide level2">
<h2>Kids’ Explanation</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p>Old basket (🧺<span class="math inline">\(_{past}\)</span>):</p>
<ul>
<li>🍎 10 apples</li>
<li>🍊 5 oranges</li>
</ul>
<p>Old prices (🏷️<span class="math inline">\(_{past}\)</span>):</p>
<ul>
<li><span class="math inline">\(p_🍎=1\)</span></li>
<li><span class="math inline">\(p_🍊=0.8\)</span></li>
</ul>
</div><div class="column" style="width:50%;">
<p>New basket (🧺<span class="math inline">\(_{today}\)</span>):</p>
<ul>
<li>🍎 8 apples</li>
<li>🍊 6 oranges</li>
</ul>
<p>New prices (🏷️<span class="math inline">\(_{today}\)</span>):</p>
<ul>
<li><span class="math inline">\(p_🍎=1.2\)</span></li>
<li><span class="math inline">\(p_🍊=1.1\)</span></li>
</ul>
</div></div>
<p>Let’s consider that the <strong>base year is past</strong>.</p>
</section>
<section id="kids-explanation---prices" class="slide level2">
<h2>Kids’ Explanation - Prices</h2>
<p><strong>Laspeyres - Price:</strong></p>
<p>Use always <span class="math inline">\(🧺_{past}\)</span>, but relevant <span class="emoji" data-emoji="label">🏷️</span>! Laspeyres Price Index (LPI):</p>
<div style="text-align: center;">
<p><small></small></p><small>
<p><span class="math display">\[🧺_{past}|\text{🏷️}_{past}\quad LPI_{past}=\frac{10\times 1 + 5 \times 0.8}{10\times 1 + 5 \times 0.8} = \frac{14}{14}=1\]</span> <span class="math display">\[🧺_{past}|\text{🏷️}_{today}\quad LPI_{today}=\frac{10\times 1.2 + 5\times 1.1}{10\times 1 + 5 \times 0.8}=\frac{17.5}{14}=1.25\]</span></p>
</small><p><small></small></p>
</div>
<blockquote>
<p>Remember that 1 corresponds to 100, and 1.25 corresponds to 125.</p>
</blockquote>
</section>
<section id="kids-explanation---prices-1" class="slide level2">
<h2>Kids’ Explanation - Prices</h2>
<p><strong>Paasche - Price:</strong></p>
<p>Use always <span class="math inline">\(🧺_{today}\)</span>! Paasche Price Index (PPI):</p>
<div style="text-align: center;">
<p><small></small></p><small>
<p><span class="math display">\[🧺_{today}|\text{🏷️}_{past}\quad PPI_{past}=\frac{8\times 1 + 6 \times 0.8}{8\times 1 + 6 \times 0.8} = \frac{12.8}{12.8}=1\]</span> <span class="math display">\[🧺_{today}|\text{🏷️}_{today}\quad PPI_{today}=\frac{8\times 1.2 + 6\times 1.1}{8\times 1 + 6 \times 0.8}=\frac{16.2}{12.8}=1.27\]</span></p>
</small><p><small></small></p>
</div>
<blockquote>
<p>Remember that 1 corresponds to 100, and 1.27 corresponds to 127.</p>
</blockquote>
</section>
<section id="in-general---laspeyres" class="slide level2">
<h2>In general - Laspeyres</h2>
<ol type="1">
<li class="fragment"><p>For prices, how much the old basket would cost at current prices relative to the <strong>old basket and prices</strong>? <span class="math display">\[LPI = \frac{\sum_{k=1}^m p_t^k q_0^k}{\sum_{k=1}^m p_0^k q_0^k}\]</span></p></li>
<li class="fragment"><p>For quantities, how much the current basket would cost at the old prices, relative to the <strong>old basket and prices</strong>? <span class="math display">\[LQI = \frac{\sum_{k=1}^m p_0^k q_t^k}{\sum_{k=1}^m p_0^k q_0^k}\]</span></p></li>
</ol>
<div class="fragment">
<blockquote>
<p>Note: denominator is the same.</p>
</blockquote>
</div>
</section>
<section id="in-general---paasche" class="slide level2">
<h2>In general - Paasche</h2>
<ol type="1">
<li class="fragment"><p>For prices, how much more expensive is the <strong>current basket</strong> at current prices, relative to the original prices. <span class="math display">\[PPI = \frac{\sum_{k=1}^m p_t^kq_t^k}{\sum_{k=1}^m p_0^kq_t^k}\]</span></p></li>
<li class="fragment"><p>For quantities, how much more the <strong>current basket</strong> costs, relative to what would cost the original basket at current prices. <span class="math display">\[PQI = \frac{\sum_{k=1}^m p_t^kq_t^k}{\sum_{k=1}^m p_t^kq_0^k}\]</span></p></li>
</ol>
<div class="fragment">
<blockquote>
<p>Note: numerator is the same.</p>
</blockquote>
</div>
</section>
<section id="conclusions" class="slide level2">
<h2>Conclusions</h2>
<ol type="1">
<li class="fragment"><p>In both index numbers, for prices, quantities are constant: All variation comes from prices.</p></li>
<li class="fragment"><p>In both index numbers, for quantities, prices are constant: All variation comes from quantities.</p></li>
</ol>
<div class="fragment">
<p><br>
</p>
<blockquote>
<p>We tend to use much more often <em>Laspeyres</em> because quantities take much longer to be accurately collected than prices. Ergo, national statistics institutes usually use Laspeyres price index to measure the price evolution.</p>
</blockquote>
</div>
</section>
<section id="fisher-index" class="slide level2">
<h2>Fisher Index</h2>
<p>Some authors argue, however, that the true measure for <em>cost of life</em> is in between both metrics. This is captured by the <strong>Fisher Index</strong>:</p>
<p><span class="math display">\[FPI_{t|0}=\sqrt{LPI_{t|0}\times PPI_{t|0}}\]</span></p>
<p><span class="math display">\[FQI_{t|0}=\sqrt{LQI_{t|0}\times PQI_{t|0}}\]</span></p>
</section>
<section id="example-9" class="slide level2">
<h2>Example</h2>
<p>Suppose you collected the following data for years 2023, 2024, and 2025, from a basket of 15 goods.</p>
<div style="text-align: center;">
<p><small></small></p><small>
<table class="caption-top">
<colgroup>
<col style="width: 16%">
<col style="width: 27%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(P-Q\)</span></th>
<th style="text-align: center;">2023</th>
<th style="text-align: center;">2024</th>
<th style="text-align: center;">2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2023</td>
<td style="text-align: center;"><span class="math inline">\(\sum_{k=1}^{15} p_{2023}^k q_{2023}^k=8562\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\sum_{k=1}^{15} p_{2023}^k q_{2024}^k=9210\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\sum_{k=1}^{15} p_{2023}^k q_{2025}^k=9920\)</span></td>
</tr>
<tr class="even">
<td>2024</td>
<td style="text-align: center;"><span class="math inline">\(\sum_{k=1}^{15} p_{2024}^k q_{2023}^k=9150\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\sum_{k=1}^{15} p_{2024}^k q_{2024}^k=9584\)</span></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td>2025</td>
<td style="text-align: center;"><span class="math inline">\(\sum_{k=1}^{15} p_{2025}^k q_{2023}^k=9657\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(\sum_{k=1}^{15} p_{2025}^k q_{2025}^k=10013\)</span></td>
</tr>
</tbody>
</table>
<p><br>
</p>
<p>What are the LPI, PPI, and FPI if we choose as a base year 2023?</p>
<table data-fragment-index="0" class="fragment">
<tbody><tr>
<th data-fragment-index="0" class="fragment">
<span class="math inline">\(t\)</span>
</th>
<th data-fragment-index="0" class="fragment">
2023
</th>
<th data-fragment-index="0" class="fragment">
2024
</th>
<th data-fragment-index="0" class="fragment">
2025
</th>
</tr>
<tr>
<td data-fragment-index="0" class="fragment">
<span class="math inline">\(LPI_{t|2023}\)</span>
</td>
<td data-fragment-index="1" class="fragment">
<span class="math inline">\(100\)</span>
</td>
<td data-fragment-index="2" class="fragment">
106.9
</td>
<td data-fragment-index="2" class="fragment">
112.8
</td>
</tr>
<tr>
<td data-fragment-index="0" class="fragment">
<span class="math inline">\(PPI_{t|2023}\)</span>
</td>
<td data-fragment-index="1" class="fragment">
<span class="math inline">\(100\)</span>
</td>
<td data-fragment-index="3" class="fragment">
104.1
</td>
<td data-fragment-index="3" class="fragment">
100.9
</td>
</tr>
<tr>
<td data-fragment-index="0" class="fragment">
<span class="math inline">\(FPI_{t|2023}\)</span>
</td>
<td data-fragment-index="1" class="fragment">
<span class="math inline">\(100\)</span>
</td>
<td data-fragment-index="4" class="fragment">
105.5
</td>
<td data-fragment-index="4" class="fragment">
106.7
</td>
</tr>
</tbody></table>
<div class="fragment" data-fragment-index="5">
<p><span class="math display">\[LPI_{2024|2023}=100\times \frac{9150}{8562} \quad PPI_{2025|2023}=100\times\frac{10013}{9920}\quad FPI_{2024|2025}=\sqrt{106.9\times 104.1}\]</span></p>
</div>
</small><p><small></small></p>
</div>
</section></section>
<section>
<section id="inflation" class="title-slide slide level1 center">
<h1>Inflation</h1>

</section>
<section id="consumer-price-index" class="slide level2">
<h2>Consumer Price Index</h2>
<p>To measure inflation, we use a Laspeyres Price Index, usually known as CPI (Consumer Price Index).</p>
<div class="fragment">
<p>To do that, the National Institute of Statistics (or the equivalent national statistical office) defines a basket, which contains a certain mix of goods and services, that is to be representative of the consumption behavior of the population.</p>
</div>
<div class="fragment">
<p>In Portugal <span class="emoji" data-emoji="portugal">🇵🇹</span>, the index has base in 2016, and, as stated above, follows a LPI formulation with small technical adjustments. This index has a monthly frequency, <em>i.e.</em> it is computed every month.</p>
</div>
</section>
<section id="consumer-price-index-1" class="slide level2">
<h2>Consumer Price Index</h2>
<p>To create a price index, you need to follow at least 3 steps.</p>
<ol type="1">
<li class="fragment">Determine representative basket: Survey families <span class="emoji" data-emoji="family_woman_woman_girl_boy">👩‍👩‍👧‍👦</span> <span class="emoji" data-emoji="family_man_woman_boy_boy">👨‍👩‍👦‍👦</span> <span class="emoji" data-emoji="family_man_man_girl_boy">👨‍👨‍👧‍👦</span></li>
<li class="fragment">Survey retail stores to find out sale prices. <span class="emoji" data-emoji="convenience_store">🏪</span></li>
<li class="fragment">Compute the index with the collected data. <span class="emoji" data-emoji="chart_with_upwards_trend">📈</span>
<ol type="1">
<li class="fragment">Compute the cost of the <span class="emoji" data-emoji="basket">🧺</span> with the prices at the base period.</li>
<li class="fragment">Compute the cost of the same <span class="emoji" data-emoji="basket">🧺</span> with the prices of every succesive period.</li>
</ol></li>
</ol>
</section>
<section id="application" class="slide level2">
<h2>Application</h2>
<p>A Labor union leader is complaining that the average salary in 2021 was 1500, and in 2024 it is 1650. This increase, they say, is not enough to maintain the workers’ purshasing power, because of inflation. The data for inflation is the following:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Year</th>
<th style="text-align: center;">2021</th>
<th style="text-align: center;">2022</th>
<th style="text-align: center;">2023</th>
<th style="text-align: center;">2024</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CPI</td>
<td style="text-align: center;">104.6</td>
<td style="text-align: center;">113</td>
<td style="text-align: center;">119</td>
<td style="text-align: center;">122.2</td>
</tr>
</tbody>
</table>
<ol type="1">
<li class="fragment">The year with the largest increase in prices was 2023?</li>
<li class="fragment">The average growth rate for the wages between 2021 and 2024 was _______?</li>
<li class="fragment">Is the union leader right?</li>
</ol>
</section>
<section id="application-1" class="slide level2">
<h2>Application</h2>
<p>For the first question, we can compute the chain or link index:</p>
<table data-fragment-index="0" class="fragment">
<tbody><tr>
<th data-fragment-index="0" class="fragment">
Year
</th>
<th data-fragment-index="0" class="fragment">
2021
</th>
<th data-fragment-index="0" class="fragment">
2022
</th>
<th data-fragment-index="0" class="fragment">
2023
</th>
<th data-fragment-index="0" class="fragment">
2024
</th>
</tr>
<tr>
<td data-fragment-index="0" class="fragment">
CPI
</td>
<td data-fragment-index="0" class="fragment">
104.6
</td>
<td data-fragment-index="0" class="fragment">
113
</td>
<td data-fragment-index="0" class="fragment">
119
</td>
<td data-fragment-index="0" class="fragment">
122.2
</td>
</tr>
<tr>
<td data-fragment-index="0" class="fragment">
CPI<sub>link</sub>
</td>
<td data-fragment-index="1" class="fragment">
—
</td>
<td data-fragment-index="2" class="fragment">
108
</td>
<td data-fragment-index="3" class="fragment">
105.3
</td>
<td data-fragment-index="4" class="fragment">
102.7
</td>
</tr>
</tbody></table>
<div class="fragment">
<p>So the answer is: The year with the largest price increase was 2022.</p>
<blockquote>
<p>Just in case there were doubts, an example: <span class="math display">\[CPI_{link|2023}=\frac{119}{113}\times 100=105.3\]</span></p>
</blockquote>
</div>
</section>
<section id="application-2" class="slide level2">
<h2>Application</h2>
<p>We know salary in 2021 was 1500, and in 2024 1650. If the growth rate was constant, say <span class="math inline">\(\delta_w\)</span> we would have:</p>
<div class="fragment">
<p><span class="math display">\[1650 = 1500(1+\delta_w)^{3}\]</span></p>
<p>Or conversely</p>
<p><span class="math display">\[\frac{1650}{1500}=(1+\delta_w)^{3}\]</span></p>
</div>
<div class="fragment">
<p>or</p>
</div>
<div class="fragment">
<p><span class="math display">\[\left(1.0312\right)^{1/3}=1+\delta_w\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[1.0103-1=\delta_w \quad \Rightarrow \quad \delta_w=0.0103= 1.03\%\]</span></p>
</div>
</section>
<section id="summarizing" class="slide level2">
<h2>Summarizing</h2>
<p>Remember this relationship we saw before? <span class="math display">\[I^q_{t|b}=\frac{I^v_{t|b}}{I^p_{t|b}}\]</span></p>
<p><strong>Real</strong> equals <strong>nominal</strong> over <strong>CPI</strong>.</p>
<p>This, dividing by CPI a nominal quantity, is known as <em>to deflate</em> by the CPI.</p>
</section>
<section id="about-the-test-for-factor-reversal-for-composite-index-numbers" class="slide level2">
<h2>About the Test for Factor Reversal for Composite Index Numbers</h2>
<p>Note that neither Laspeyres nor Paasche pass the test for <strong>factor reversal</strong> (<a href="#factor-reversal">see here</a>), <span class="math display">\[VI_{t|0}\neq LPI_{t|0}\times LQI_{t|0}\quad\quad VI_{t|0}\neq PPI_{t|0}\times PQI_{t|0}\]</span></p>
<p>But we can verify that: <span class="math display">\[LPI_{t|0}\times PQI_{t|0}=IV_{t|0} \quad \quad PPI_{t|0}\times LQI_{t|0}=IV_{t|0}\]</span></p>
</section>
<section id="about-the-test-for-factor-reversal-for-composite-index-numbers-1" class="slide level2">
<h2>About the Test for Factor Reversal for Composite Index Numbers</h2>
<p>(… continuation)</p>
<p>Example (do the rest as homework): <span class="math display">\[LPI_{t|0}\times PQI_{t|0}=\frac{\sum_{k=1}^m p_t^kq_0^k}{\sum_{k=1}^m p_0^kq_0^k}\frac{\sum_{k=1}^m p_t^kq_t^k}{\sum_{k=1}^m p_t^kq_0^k}=\frac{\sum_{k=1}^m p_t^kq_t^k}{\sum_{k=1}^m p_0^kq_0^k}\]</span></p>
<p>Note that this last item is exactly <span class="math inline">\(IV_{t|0}\)</span>.</p>
<div class="fragment">
<p>You can verify, using the same procedure, that Fisher’s index does indeed passess the factor reversal test.</p>
</div>
</section>
<section id="about-the-factor-reversal-test-for-composite-index-numbers" class="slide level2">
<h2>About the Factor Reversal Test for Composite Index Numbers</h2>
<p><span class="math display">\[FPI_{t|0}\times FQI_{t|0}=\]</span> <span class="math display">\[\sqrt{LPI_{t|0}\times PPI_{t|0}}\times\sqrt{LQI_{t|0}\times PQI_{t|0}}\]</span> <span class="math display">\[\sqrt{LPI_{t|0}\times PPI_{t|0}\times LQI_{t|0}\times PQI_{t|0}}\]</span> <span class="math display">\[\sqrt{LPI_{t|0}\times PQI_{t|0}\times LQI_{t|0}\times PPI_{t|0}}\]</span> <span class="math display">\[\sqrt{IV_{t|0}\times IV_{t|0}}=\sqrt{IV_{t|0}^2}\]</span> <span class="math display">\[IV_{t|0}\]</span></p>
</section>
<section id="about-the-time-reversal-test-for-composite-index-numbers" class="slide level2">
<h2>About the Time Reversal Test for Composite Index Numbers</h2>
<p>Laspeyres and Paasche do not pass the time Reversal test, let’s see an example:</p>
<p><span class="math display">\[LPI_{t|0}\times LPI_{0|t} = \frac{\sum_{k=1}^m p_t^k q_0^k}{\sum_{k=1}^m p_0^k q_0^k}\frac{\sum_{k=1}^m p_0^k q_t^k}{\sum_{k=1}^m p_t^k q_t^k}\neq 1\]</span></p>
<p>You can do the same for Paasche, and for the quantities index numbers.</p>
</section>
<section id="about-the-time-reversal-test-for-composite-index-numbers-1" class="slide level2" data-transition="none">
<h2>About the Time Reversal Test for Composite Index Numbers</h2>
<p>Fisher on the other hand…</p>
<p><span class="math display">\[FPI_{t|0}\times FPI_{0|t}=\sqrt{LPI_{t|0}PPI_{t|0}}\sqrt{LPI_{0|t}PPI_{0|t}}\]</span></p>
<div class="fragment">
<p><span class="math display">\[=\sqrt{\frac{\sum_{k=1}^m p_t^k q_0^k}{\sum_{k=1}^m p_0^k q_0^k}\frac{\sum_{k=1}^m p_t^k q_t^k}{\sum_{k=1}^m p_0^k q_t^k}}\sqrt{\frac{\sum_{k=1}^m p_0^k q_t^k}{\sum_{k=1}^m p_t^k q_t^k}\frac{\sum_{k=1}^m p_0^k q_0^k}{\sum_{k=1}^m p_t^k q_0^k}}\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[=\sqrt{\frac{\sum_{k=1}^m p_t^k q_0^k}{\sum_{k=1}^m p_0^k q_0^k}\frac{\sum_{k=1}^m p_t^k q_t^k}{\sum_{k=1}^m p_0^k q_t^k}\frac{\sum_{k=1}^m p_0^k q_t^k}{\sum_{k=1}^m p_t^k q_t^k}\frac{\sum_{k=1}^m p_0^k q_0^k}{\sum_{k=1}^m p_t^k q_0^k}}\]</span></p>
</div>
</section>
<section id="about-the-time-reversal-test-for-composite-index-numbers-2" class="slide level2" data-transition="none">
<h2>About the Time Reversal Test for Composite Index Numbers</h2>
<p>Fisher on the other hand…</p>
<p><span class="math display">\[FPI_{t|0}\times FPI_{0|t}=\sqrt{LPI_{t|0}PPI_{t|0}}\sqrt{LPI_{0|t}PPI_{0|t}}\]</span></p>
<p><span class="math display">\[=\sqrt{\frac{\sum_{k=1}^m p_t^k q_0^k}{\sum_{k=1}^m p_0^k q_0^k}\frac{\sum_{k=1}^m p_t^k q_t^k}{\sum_{k=1}^m p_0^k q_t^k}}\sqrt{\frac{\sum_{k=1}^m p_0^k q_t^k}{\sum_{k=1}^m p_t^k q_t^k}\frac{\sum_{k=1}^m p_0^k q_0^k}{\sum_{k=1}^m p_t^k q_0^k}}\]</span></p>
<p><span class="math display">\[=\sqrt{\frac{\color{red}{\sum_{k=1}^m p_t^k q_0^k}}{\color{blue}{\sum_{k=1}^m p_0^k q_0^k}}\frac{\color{green}{\sum_{k=1}^m p_t^k q_t^k}}{\sum_{k=1}^m p_0^k q_t^k}\frac{\sum_{k=1}^m p_0^k q_t^k}{\color{green}{\sum_{k=1}^m p_t^k q_t^k}}\frac{\color{blue}{\sum_{k=1}^m p_0^k q_0^k}}{\color{red}{\sum_{k=1}^m p_t^k q_0^k}}}\]</span></p>
<div class="fragment">
<p><span class="math display">\[FPI_{t|0}\times FPI_{0|t}=1\]</span></p>
</div>
</section>
<section id="about-the-circularity-test-for-composite-index-numbers" class="slide level2">
<h2>About the Circularity Test for Composite Index Numbers</h2>
<p>None, not even Fisher’s Index pass the circularity test.</p>
<blockquote>
<p>Homework: Verify it.</p>
</blockquote>
</section>
<section id="example-10" class="slide level2">
<h2>Example</h2>
<table>
<tbody><tr>
<th>
</th>
<th colspan="2">
Year 1
</th>
<th colspan="2">
Year 2
</th>
</tr>
<tr>
<td>
Public Transportation
</td>
<td>
N Trips
</td>
<td>
Ticket price
</td>
<td>
N Trips
</td>
<td>
Price Index (base = Year 1)
</td>
</tr>
<tr>
<td>
Bus
</td>
<td>
1,763,521
</td>
<td>
1.15
</td>
<td>
1,875,345
</td>
<td>
108.7
</td>
</tr>
<tr>
<td>
Metro
</td>
<td>
3,148,350
</td>
<td>
1.2
</td>
<td>
3,396,138
</td>
<td>
112.5
</td>
</tr>
</tbody></table>
</section>
<section id="example-11" class="slide level2">
<h2>Example</h2>
<ol type="1">
<li class="fragment">According to LPI for year 2, prices for public transportantion grew 11.17%.</li>
<li class="fragment">Real change, according to Paasche, for public transportation was 7.35%.</li>
<li class="fragment">The composite index for change in expenditures with public transportation in year 2 compared the expenditure in year 1 is what type of change? (real, nominal, quantity, prices?) How much was it?</li>
</ol>
</section>
<section id="example-12" class="slide level2">
<h2>Example</h2>
<p><strong>According to LPI for year 2, prices for public transportantion grew 11.17%.</strong></p>
<div class="fragment">
<p>First, we need to find <span class="math inline">\(p_2\)</span> for bus and metro.</p>
</div>
<div class="fragment">
<p><span class="math display">\[108.7=\frac{p_2^{bus}}{1.15}\times 100\]</span></p>
</div>
<div class="fragment">
<p>Or <span class="math inline">\(p_2^{bus}=1.25\)</span></p>
<p><span class="math display">\[112.5=\frac{p_2^{metro}}{1.2}\]</span></p>
<p>Or <span class="math inline">\(p_2^{metro}=1.35\)</span></p>
</div>
</section>
<section id="example-13" class="slide level2">
<h2>Example</h2>
<table>
<tbody><tr>
<th>
</th>
<th colspan="2">
Year 1
</th>
<th colspan="2">
Year 2
</th>
</tr>
<tr>
<td>
Public Transportation
</td>
<td>
N Trips
</td>
<td>
Ticket price
</td>
<td>
N Trips
</td>
<td>
Ticket price
</td>
</tr>
<tr>
<td>
Bus
</td>
<td>
1,763,521
</td>
<td>
1.15
</td>
<td>
1,875,345
</td>
<td>
1.25
</td>
</tr>
<tr>
<td>
Metro
</td>
<td>
3,148,350
</td>
<td>
1.2
</td>
<td>
3,396,138
</td>
<td>
1.35
</td>
</tr>
</tbody></table>
</section>
<section id="example-14" class="slide level2">
<h2>Example</h2>
<p><span class="math display">\[LPI_{2|1}=\frac{\sum_{k=1}^m p_2^k q_1^k}{\sum_{k=1}^m p_1^k q_1^k}\]</span></p>
<div class="fragment">
<p><span class="math display">\[LPI_{2|1}=\frac{1,763,521\times 1.25 + 3,148,350 \times 1.35}{1,763,521\times 1.15 + 3,148,350 \times 1.2}\]</span></p>
</div>
<div class="fragment">
<p><span class="math display">\[LPI_{2|1}=1.1117\]</span></p>
</div>
<div class="fragment">
<blockquote>
<p>The <em>basket</em> in year 2 is 11.17% more expensive than in year 1. <span class="math display">\[LPI_{2|1}\times 100 - 100 = 11.17\%\]</span></p>
</blockquote>
</div>
</section>
<section id="example-15" class="slide level2">
<h2>Example</h2>
<p><strong>Real change, according to Paasche, for public transportation was 7.35%.</strong></p>
<p><span class="math display">\[PQI_{2|1}=\frac{\sum_{k=1}^m p_2^k q_2^k}{\sum_{k=1}^m p_2^k q_1^k}\]</span></p>
<p><span class="math display">\[PQI_{2|1}=\frac{1,875,345\times 1.25 + 3,396,138\times 1.35}{1,763,521\times 1.25 + 3,148,350\times 1.35}\]</span></p>
<p><span class="math display">\[PQI_{2|1}=1.0735\]</span></p>
<blockquote>
<p>Indeed, according to the Paasche index, in year 2 the amount of public transportantion trips was 7.35% larger than in year 1. <span class="math display">\[PQI_{2|1}\times 100 - 100 = 7.35\%\]</span></p>
</blockquote>
</section>
<section id="example-16" class="slide level2">
<h2>Example</h2>
<p><strong>The composite index for change in expenditures with public transportation in year 2 compared the expenditure in year 1 is what type of change? (real, nominal, quantity, prices?) How much was it?</strong></p>
<p>The value index for public transportation is a <em>nominal</em> index (price times quantity).</p>
<div class="fragment">
<blockquote>
<p><strong>Remember:</strong> <span class="math display">\[VI_{t|0}=LPI_{t|0}\times PQI_{t|0}\]</span></p>
</blockquote>
</div>
</section>
<section id="example-17" class="slide level2">
<h2>Example</h2>
<p><span class="math display">\[VI_{2|1}=LPI_{2|1}\times PQI_{2|1} = 1.1117 \times 1.0735 \approx 1.1934\]</span></p>
<p>The value of publc transportation trips grew 19.34% from year 1 to year 2. This includes the effect of an increase in prices and quantities.</p>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Statistics I</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="1_intro_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="1_intro_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="1_intro_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="1_intro_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="1_intro_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="1_intro_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="1_intro_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="1_intro_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="1_intro_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="1_intro_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>