---
title: "Syllabus - Bridging Mathematics"
author: "Paulo Fagandini"
format: html
lang: en
editor: source
page-layout: full

---

PhD in Economics and Finance\
Academic Year: 2025/2026\
Course Unit: Bridging Mathematics

Instructor: Paulo Fagandini\
:email: : paulo.fagandini@novasbe.pt

Year: 1st Year\
Weekly Hours: 22.5 Hours\
ECTS: 0

### Short bio

I am a Commercial Engineer from the UChile. I hold a PhD in Economics from Nova SBE. After completing a postdoc in Finance, here at Nova as well, I became Assistant Professor of Economics (Adjunct) at ISCAL-IPL and at Nova SBE, and research member of CEFAGE Research Center. My research focuses on applied microeconomic theory, computational economics, and empirical corporate finance. My current teaching duties are bachelor’s Economics, Microeconomics, Statistics I, and Statistics II at ISCAL-IPL. At Nova SBE my teaching duties includes, besides this course, the master’s Math & Stats.

### General Objective

The course should provide a coverage of the basic mathematical concepts students should be familiar with before entering the coursework of the doctorate. Furthermore, they will be exposed to some proof techniques and mathematical methods. If time permits, we will also cover some pieces of software that could prove useful for the students throughout the semester.

### Course unit contents

Functions, Topology and Continuity, Differentiation, Linear Algebra, Differential Equations, Static and Dynamic Optimization, Probability Theory, and Markov Chains.

### Learning Outcomes

Students should become familiarized with basic mathematical concepts that are crucial for the understanding of the subsequent doctoral courses. Moreover, they should be familiarized with proof techniques and the use of some classical theorems.

### Syllabus

1. Set theory [8]
2. Functions [8]
3. Topology and Continuity [1, 8]
4. Concavity and Quansiconcavity [3]
5. Vectors and Vector Spaces [8]
6. Matrices [8]
7. Differentiation [8]
8. Static Optimization [2, 3]
9. Differential Equations [2]
10. Dynamic Optimization: Discrete Case, Euler Equations
11. Optimal Control [2]
12. The Ramsey-Cass-Koopmans Growth Model [2]
<!-- 13. Introduction to Measure and Integration [4] -->
14. Review of Probability Theory [7]
15. The Central Limit Theorem
16. Markov Chains [7]

### Assessment Methods

There is no assessment.


### Bibliography

1. “Advanced Mathematical Economics”, Rakesh V. Vohra
2. “Mathematical Methods and Models for Economists”, Angel de la Fuente
3. “Mathematics for Economists”, Carl P. Simon and Lawrence E. Blume
4. "Real Analysis for Graduate Students: Measure and Integration Theory", Richard F. Bass
5. “Introduction to Analysis”, Maxwell Rosenlicht
6. "Statistical Inference" 2E, George Casella and Roger L. Berger
7. “Introduction to Probability”, Dimitri P. Bertsekas and John N. Tsitsiklis (*)
8. “Apuntes de matemáticas para economía” [Lecture Notes], Jorge Rivera. (*)
9. “The Structure of Economics: A Mathematical Analysis”, Eugene Silberberg and Wing Suen
10. “Advanced Microeconomic Theory”, Geoffrey Jehle and Philip Reny.
11. "Introdução à Economia Matemática, Aloísio Araújo"